### ISSUE TITLE
Autotier now installed on Debian/TrueNAS. A few questions.

### ISSUE THREAD

**Issue by MostHated** [45Drives/autotier#54]
Hey there, thanks for the Debian release, I grabbed that and I now have this setup on TrueNAS for the most part. I made a reply and a few edits to my last thread, but wasn't sure if you would see it since it was closed, so I figured it was best to make a new one.

I am not sure if this is a TrueNAS specific thing or a ZFS thing or what, but in TrueNAS I tried to create a NFS share via the interface which was the folder I used in which to mount Autotier (/mnt/share), but it is saying that in order to do so the mount has to be within a ZFS pool, either /mnt/ssddata (/mnt/ssddata/data is the actual point in which Autotier is configured, same for hdd) or /mnt/hddata, my two arrays I wanted to tier. Is there anything special I need to do or know about trying to share the Autotier mounted location? I am not sure if having my combined autotier amount point being on one of the arrays is ok or not?

Also, I saw mentioned of adding use to the Autotier group, but I don't see one. Was it supposed to be made automatically, or am I supposed to make it and then add something to it? 

Thanks,
-MH

**Comment by joshuaboud** [comment]
Hi,
ZFS implements a way to create an NFS share with the `zfs set share` command, which only works for ZFS datasets. Since TrueNAS is entirely ZFS, I'm 90% sure this is what is being used in the back end to create shares, rather than the traditional way of creating an NFS share from anywhere. You could try to manually create a share through the command line to export your autotier mount point, but I don't think it could be managed through the UI afterwards.

If you're interested in an alternative to TrueNAS, 45Drives has their own web UI based on the Cockpit Project from RedHat called Houston. Setup isn't too difficult - from a fresh install of Ubuntu Focal (20.04), you can follow these steps to set it up:
1. [Configuring a Fresh Install of Ubuntu for Houston UI](https://knowledgebase.45drives.com/kb/kb450290-configuring-fresh-install-of-ubuntu-20-04lts-for-houston-ui/)
2. [Install Houston Modules](https://knowledgebase.45drives.com/kb/kb451401-installing-houston-july-2021-modules/)
3. [Creating and Managing ZFS Pools](https://knowledgebase.45drives.com/kb/kb450310-creating-a-storage-pool-and-filesystem-in-houston-ui/)  

With these modules, you can use the ZFS tab to manage your pools, and the File Sharing tab to mange the NFS share.

You could also try having the mount point in one of the arrays, I'm just not sure if TrueNAS will allow it to be shared because of the filesystem no longer being ZFS at that mount point. Wouldn't hurt to try though.

As for the autotier group, it was supposed to have been added on installation. After looking at the packaging files, I realized I forgot to include the postinstall script. I'll make a new release shortly with that fixed. In the mean time, you can create it yourself with `sudo groupadd autotier`. The group is only needed if you want to manage autotier as a non-root user.

**Comment by MostHated** [comment]
Thanks for the info, I was just about to reply to this when your reply came in. I got it working and shared for the most part last night. The folders all look good, but no actual files show up in nemo, then when I went into the combined drive view in the terminal, I noticed everything currently looks like this below: I am assuming that I must have missed something, and it is probably something permission related or similar.

![](https://i.imgur.com/wUDVStb.png)

**Comment by joshuaboud** [comment]
Were there already files in the tiers before using autotier?

**Comment by joshuaboud** [comment]
Only way I could recreate this myself was by moving files directly into a tier after autotier has been mounted. If this is what happened, just unmount autotier and then remount it, and add files through the mount point in the future. Let me know if this is not the case.

**Comment by MostHated** [comment]
Yeah, that was a big part of wanting a system like this, I was getting tired of trying to manage the back and forth of moving things manually between ssd and hdd manually as I needed to use certain things more/less. I did this, though, keeping in mind that I should not have a duplicate file structure between the two, so as far as I know, there should not have been the same file at the same path anywhere. Everything that is currently there was there before I set up autotier, and nothing new had been added. I did go through and do the init sequence to duplicate the hierarchy, though. I am not sure if any of this is related to not having an autotier group or any of the post install stuff?

I just saw your new reply, though, so I will give that a try and see if remounting does the trick and report back.

**Comment by MostHated** [comment]
Hmm... what I did was unshared the NFS share, then tried to unmount the folder but it said it was busy, so I restarted, and since I didn't have autotier setup yet to automount, it was just a blank share folder, so I then used `sudo autotierfs /mnt/ssdarray/share -o allow_other,default_permissions`, which made all the folders appear, then reshared that folder via NFS and went to it from another PC but still see the same thing it looks like. 

What I can try is, perhaps start pulling things off of the underlying drive and then adding them to the autotier combined mount, just to see if that then makes it show up and work properly.

**Comment by joshuaboud** [comment]
You can try nuking the autotier metadata directory before remounting. If it says it's busy while trying to unmount, do:
1. `sudo umount autotier -l` (maybe run this more than once until it says it's not mounted in case it's mounted on top of itself)
2. `sudo killall -9 autotierfs`
3. `sudo rm /var/lib/autotier/* -rf`
4. `sudo autotierfs /mnt/ssdarray/share -o allow_other,default_permissions`

**Comment by MostHated** [comment]
I tried what you mentioned, but unfortunately has the same result. I am starting to think it might have something to do with particular files, possibly ones that were originally made/added to the disk via Windows. I typically had multiple machines using the shares, one being my work laptop, which is windows 10 setup to use NFS and I had several folders of code that were made on that laptop and added to the disk. 

I wanted to try what I mentioned, I removed a folder from the ssd array and brought it to my local disk, then put it back on the autotier combined share and it showed up, all files were there. Those files were all created by and only ever used from my Linux desktop. Then I tried the code folder, as soon as I put that on there the same way, none of the files showed up and the top level folder showed as empty. It *could* be coincidence, but also, the files that I showed in my prior screenshot had all originated from a windows machine as well. There were a number of those files in which I had to run the following on when trying to get them to show up at all.

```
find . -type d -print0 | xargs -0 chmod 755 
find . -type f -print0 | xargs -0 chmod 644 
```

But the more I look at the folders, the top level ones that have subfolders and files that were accessed by windows show as blank folders, while other ones in which I only ever remember accessing from my Linux boxes seem to at least show the top level folder as having contents and not just empty.

**Comment by joshuaboud** [comment]
When you get question marks in ls like that, it's usually from autotier not knowing the backend paths (real paths on the underlying tiers) to be able to return the actual file metadata. I don't think permissions or Windows would cause it but you never know. Modifying permissions most likely won't help though as the filesystem inherently runs as root. The database relating paths relative to the mountpoint to the back end tier paths for files is in /var/lib/autotier, so nuking that directory and remounting kind of resets autotier. I'll keep this open for now in case I run into the issue myself at some point and find a solution, but for now I can't think of any other causes or potential solutions. Just keep in mind that if you get autotier working, make sure that files are only accessed through the autotier mountpoint and not directly through the underlying tier.

**Comment by MostHated** [comment]
Understood, and I appreciate the assistance. What I can do is move some of the stuff I use daily to my unraid server for now so as not to mess with any of the underlying paths as you mentioned, so that I can play around with it a bit more without the chance of one of the other boxes changing anything until I get things working and can remap it all to the combined share.
